config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    resources :collaborators
  end

  resources :charges, only: [:new, :create, :edit]

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize :init

  ## after_create :send_email

  def send_email
    UserMailer.send_email(self).deliver_now
  end

  def init
    self.role  ||= :standard   
  end

  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  class Amount
    def self.default
      15_00
    end
  end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
  
    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )
    current_user.premium!
    flash[:notice] = "Congrats #{current_user.email} you are now a Premium Member!!"
    redirect_to wikis_path # or wherever
  
    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership",
      amount: Amount.default
    }
  end

  def edit
    @charge = Stripe::Charge.list.data[0].id
    newArray = Wiki.where(user_id: current_user.id)
    newArray.each do |w|
      w.private = false
      w.save
    end
    current_user.standard!
    flash[:alert] = "We are sorry to see you go"
    redirect_to wikis_path
  end

  def update
    current_user.standard!
    flash[:alert] = "We are sorry to see you go"
    redirect_to wikis_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def index 
    @collaborators = Collaborator.all 
  end 

  def show
    @collaborator = Collaborator.find(params[:wiki_id])
  end

  def new
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new
  end

  def create 
    @wiki = Wiki.find(params[:wiki_id])
    collaborator = @wiki.collaborators.new(collaborator_params)
    
    if collaborator.save
      flash[:notice] = "Collaborator added"
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end


  def edit
    @collaborator = Collaborator.find(params[:id])
  end

  def destroy
    @collaborator = Collaborator.find(params[:wiki_id])

    if @collaborator.destroy
      flash[:notice] = "\"#{@collaborator.email}\" was removed from collaborators."
      redirect_to wiki_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  def update

  end

  private
  def collaborator_params
    params.require(:collaborator).permit(:email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
      @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
      @wiki = Wiki.new
      authorize @wiki
  end

  def create
      @wiki = Wiki.create(wiki_params)
      @wiki.title = params[:wiki][:title]
      @wiki.body = params[:wiki][:body]

      @wiki.user = current_user

      authorize @wiki

      if @wiki.save
        flash[:notice] = "Wiki was saved"
        redirect_to @wiki
      else
        flash.now[:alert] = "Error saving Wiki"
        render :new
      end 
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]

    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown
    Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/edit.html.erb
<h1> Edit </h1>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h2>Upgrade to Premium!!</h2>
  <h4> Premium benefits <h4>
  <ul>
    <li> Create private wikis </li>
    <li> Make public wikis private </li>
  </ul>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/edit.html.erb
<h1>Collaborators#edit</h1>
<p>Find me in app/views/collaborators/edit.html.erb</p>

app/views/collaborators/new.html.erb
<h1>Add Collaborators </h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for [@wiki, @collaborator] do |c| %>
      <div class="form-group">
        <%= c.label :email %>
        <%= c.text_field :email, class: 'form-control', placeholder: "Enter collaborator email" %>
      </div>
      <div class="form-group">
        <%= c.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/collaborators/show.html.erb
<h3>Collaborator email: <%= @collaborator.email %></h3> 

<%= link_to "Remove collaborator", @wiki, method: :delete, class: 'btn btn-sq-sm btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name=> 'stripe-key', :content => ENV[":publishable_key"] %>
  </head>

  <body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <% if current_user == nil %>
        <li></li>
      <% elsif current_user.role == 'premium' %>
        <li><%= link_to "Premium Member", edit_user_registration_path %></li>
      <% elsif current_user.role == 'admin' %>
        <li><%= link_to "Admin", edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to "Upgrade to Premium", new_charge_path %>
      <% end %>  
    </ul>
    <% if user_signed_in? %>
      Signed in as: <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h3> <strong>Blocipedia </strong>is a host of knowledge from the seas to the ocean, which I believe is the same thing. Its just a great place to be. </h3>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia </h1>
<img src="https://static.pexels.com/photos/311269/pexels-photo-311269.jpeg">

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Editing Knowledge on the Internet</p>
    <ul>
      <li>Its a big responsiblity</li>
      <li>Don't swear</li>
      <li>Dont troll in the comment section</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |w| %>
      <div class="form-group">
        <%= w.label :title %>
        <%= w.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= w.label :body %>
        <%= w.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
        <%= w.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
    <% if @wiki.private == true %>
      <% if @wiki.collaborators.empty? %>
        <h5> No collaborators yet </h5>
        <%= link_to "Add Collaborators", new_wiki_collaborator_path(@wiki), class: 'btn btn-sq-sm btn-primary' %>
      <% else %>
        <h4> Collaborators </h4>
        <% @wiki.collaborators.each do |c| %>
          <div class="media">
            <div class="media-body">
              <h8 class="media-heading">
                <p><%= link_to c.email, wiki_collaborator_path(c.id) %></p>
              </h8>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>The Wealth of Knowledge from all Wikis lies before You</h1>

<%= link_to "New", new_wiki_path(@wiki), class: 'btn btn-sq-sm btn-success' %>

<% user = current_user %>

<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <p><%= link_to wiki.title, wiki_path(wiki.id) %></p>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Inserting Knowledge on the Internet</p>
    <ul>
      <li>Its a big responsiblity</li>
      <li>Don't swear</li>
      <li>Dont troll in the comment section</li>
    </ul>The incessant use of hashtags will get you banned.</li>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |w| %>
      <div class="form-group">
        <%= w.label :title %>
        <%= w.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= w.label :body %>
        <%= w.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= w.label :private, class: 'checkbox' do %>
        <%= w.check_box :private %> Private wiki
        <% end %>
      </div>
      <% end %>
      <div class="form-group">
        <%= w.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1> 

<%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-sq-sm btn-info' %>
<%= link_to "Delete", [ @wiki], method: :delete, class: 'btn btn-sq-sm btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
<br>

<h5> Collaborators </h5>

<% @wiki.collaborators.each do |c| %>
  <div class="media">
    <div class="media-body">
      <h8 class="media-heading">
        <p><%=  c.email %></p>
      </h8>
    </div>
  </div>
<% end %>

<h4> Content </h4>

<p><%= markdown.render(@wiki.body).html_safe %></p>